# Use vim to scroll tmux
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

# Set true color
set-option -ga terminal-overrides ",xterm*:Tc"


# Set time to escape Vim insert mode 
# Don't set to 0: 
set -sg escape-time 5

# Set leader key to space
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

# Bind new panes to start in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Floating terminal popup
bind g display-popup -E -w 80% -h 80% -d "#{pane_current_path}"

# Navigate around tmux windows/panes using vim commands 
set -g @plugin 'christoomey/vim-tmux-navigator'

bind -n C-h run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"


# Flow colorscheme | Tmux
# https://github.com/0xstepit/flow.nvim

## Statusbar style

set -g status-position bottom
set -g status-right-length "100"
set -g status-left-length "100"
set -g status-style bg=#141A1F,fg=#C8D0D7
set -g status-interval 1

# Window status styling
set -g window-status-style fg=#3D4F5C,bg=#141A1F
setw -g window-status-separator ""
set -g window-status-format "#[fg=#3D4F5C,bg=#141A1F] #I #W "
set -g window-status-current-format "#[fg=#141A1F,bg=#75BDF0,bold] #I #W #[fg=#75BDF0,bg=#141A1F]"

# Status bar left side - session name
set -g status-left "#[fg=#0D0D0D,bg=#75BDF0,bold] #S #[fg=#75BDF0,bg=#141A1F] "

# Status bar right side - git branch, time and date
set -g status-right "#[fg=#3D4F5C]#[fg=#75BDF0,bg=#1C2127] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '') #[fg=#3D4F5C]#[fg=#C8D0D7,bg=#1C2127] %H:%M  %d %b "

set -g message-command-style fg=#FF007C,bg=#1C2127
set -g message-style "fg=#FF007C,bg=#1C2127"

set -g mode-style "fg=#141A1F,bg=#75BDF0"

## Borders
set -g pane-border-style "fg=#1C2127"
set -g pane-active-border-style "fg=#75BDF0"

set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
